# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  setup:
    working_directory: ~/project
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          when: on_success
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/project
          paths: ./*

  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:6.11
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm test

  lint:
    working_directory: ~/project
    docker:
      - image: circleci/node:6.11
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run -s lint

  outdated:
    working_directory: ~/project
    docker:
      - image: circleci/node:6.11
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run -s test:outdated

workflows:
  version: 2
  default:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - outdated:
          requires:
            - setup
