name: default

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta

permissions:
  contents: read      # semantic-release needs this to publish GitHub releases/tags

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - uses: github/super-linter/slim@v7
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_EDITORCONFIG: true
        VALIDATE_YAML: true
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
        FILTER_REGEX_EXCLUDE: CHANGELOG.md

  test:
    name: nodejs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodeVersion: [20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Use Node.js ${{ matrix.nodeVersion }}
      uses: actions/setup-node@v6.3.0
      with:
        node-version: ${{ matrix.nodeVersion }}
        cache: 'npm'
    - run: npm ci --no-audit --ignore-scripts
    - run: npm test
    - uses: actions/upload-artifact@v7
      with:
        name: code-coverage-report-node-${{ matrix.nodeVersion }}
        path: coverage
        retention-days: 90

  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ matrix.nodeVersion }}
          cache: 'npm'
      - run: npm ci --no-audit --ignore-scripts
      - run: npm run start -- help

  release:
    # ignore pull-requests created by dependabot as it doesn’t has access
    # to the secrets used
    if: ${{ github.event_name == 'push' && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: write      # semantic-release needs this to publish GitHub releases/tags
      issues: write        # if you use the GitHub-release/comment plugins
      pull-requests: write # same
      id-token: write      # required for OIDC trusted publishing
    needs:
      - test
      - smoke-test
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 22
          check-latest: true
          cache: npm
      - run: npm ci --no-audit --ignore-scripts
      - run: npm install -g npm@latest
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
