name: release-please

on:
  push:
    branches:
      - master
      - alpha

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          target-branch: ${{ github.ref_name }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --no-audit --ignore-scripts
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --provenance --tag alpha
        if: ${{ steps.release.outputs.release_created && github.ref_name == 'alpha' }}

      - run: npm publish --provenance
        if: ${{ steps.release.outputs.release_created && github.ref_name == 'master' }}
