name: test

on: [push]

jobs:
  build:
    name: nodejs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodeVersion: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.nodeVersion }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodeVersion }}
    - name: npm install, build, and test
      run: npm ci
    - name: eslint
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        eslint: true
    - name: depcheck
      if: matrix.nodeVersion == '14.x'
      run: npm run -s depcheck
    - name: test
      run: npm test
      env:
        CI: true
    - name: Jest Lcov Reporter
      uses: vebr/jest-lcov-reporter@v0.2.1
      # only run this step when node version matches
      if: matrix.nodeVersion == '14.x'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
        update-comment: true
